// Code generated by "stringer -type=Operand -trimprefix=Op"; DO NOT EDIT.

package bmr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInit-0]
	_ = x[OpFxLambda-1]
	_ = x[OpFxR-2]
}

const _Operand_name = "InitFxLambdaFxR"

var _Operand_index = [...]uint8{0, 4, 12, 15}

func (i Operand) String() string {
	if i >= Operand(len(_Operand_index)-1) {
		return "Operand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operand_name[_Operand_index[i]:_Operand_index[i+1]]
}
